
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Remote` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Remote
 * 
 */
export type RemoteModel = runtime.Types.Result.DefaultSelection<Prisma.$RemotePayload>

export type AggregateRemote = {
  _count: RemoteCountAggregateOutputType | null
  _avg: RemoteAvgAggregateOutputType | null
  _sum: RemoteSumAggregateOutputType | null
  _min: RemoteMinAggregateOutputType | null
  _max: RemoteMaxAggregateOutputType | null
}

export type RemoteAvgAggregateOutputType = {
  id: number | null
  latestId: number | null
}

export type RemoteSumAggregateOutputType = {
  id: number | null
  latestId: number | null
}

export type RemoteMinAggregateOutputType = {
  id: number | null
  type: string | null
  config: string | null
  latestId: number | null
  lastFetched: Date | null
  isFetching: boolean | null
}

export type RemoteMaxAggregateOutputType = {
  id: number | null
  type: string | null
  config: string | null
  latestId: number | null
  lastFetched: Date | null
  isFetching: boolean | null
}

export type RemoteCountAggregateOutputType = {
  id: number
  type: number
  config: number
  latestId: number
  lastFetched: number
  isFetching: number
  _all: number
}


export type RemoteAvgAggregateInputType = {
  id?: true
  latestId?: true
}

export type RemoteSumAggregateInputType = {
  id?: true
  latestId?: true
}

export type RemoteMinAggregateInputType = {
  id?: true
  type?: true
  config?: true
  latestId?: true
  lastFetched?: true
  isFetching?: true
}

export type RemoteMaxAggregateInputType = {
  id?: true
  type?: true
  config?: true
  latestId?: true
  lastFetched?: true
  isFetching?: true
}

export type RemoteCountAggregateInputType = {
  id?: true
  type?: true
  config?: true
  latestId?: true
  lastFetched?: true
  isFetching?: true
  _all?: true
}

export type RemoteAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Remote to aggregate.
   */
  where?: Prisma.RemoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Remotes to fetch.
   */
  orderBy?: Prisma.RemoteOrderByWithRelationInput | Prisma.RemoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RemoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Remotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Remotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Remotes
  **/
  _count?: true | RemoteCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RemoteAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RemoteSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RemoteMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RemoteMaxAggregateInputType
}

export type GetRemoteAggregateType<T extends RemoteAggregateArgs> = {
      [P in keyof T & keyof AggregateRemote]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRemote[P]>
    : Prisma.GetScalarType<T[P], AggregateRemote[P]>
}




export type RemoteGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RemoteWhereInput
  orderBy?: Prisma.RemoteOrderByWithAggregationInput | Prisma.RemoteOrderByWithAggregationInput[]
  by: Prisma.RemoteScalarFieldEnum[] | Prisma.RemoteScalarFieldEnum
  having?: Prisma.RemoteScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RemoteCountAggregateInputType | true
  _avg?: RemoteAvgAggregateInputType
  _sum?: RemoteSumAggregateInputType
  _min?: RemoteMinAggregateInputType
  _max?: RemoteMaxAggregateInputType
}

export type RemoteGroupByOutputType = {
  id: number
  type: string
  config: string
  latestId: number | null
  lastFetched: Date | null
  isFetching: boolean
  _count: RemoteCountAggregateOutputType | null
  _avg: RemoteAvgAggregateOutputType | null
  _sum: RemoteSumAggregateOutputType | null
  _min: RemoteMinAggregateOutputType | null
  _max: RemoteMaxAggregateOutputType | null
}

export type GetRemoteGroupByPayload<T extends RemoteGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RemoteGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RemoteGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RemoteGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RemoteGroupByOutputType[P]>
      }
    >
  >



export type RemoteWhereInput = {
  AND?: Prisma.RemoteWhereInput | Prisma.RemoteWhereInput[]
  OR?: Prisma.RemoteWhereInput[]
  NOT?: Prisma.RemoteWhereInput | Prisma.RemoteWhereInput[]
  id?: Prisma.IntFilter<"Remote"> | number
  type?: Prisma.StringFilter<"Remote"> | string
  config?: Prisma.StringFilter<"Remote"> | string
  latestId?: Prisma.IntNullableFilter<"Remote"> | number | null
  lastFetched?: Prisma.DateTimeNullableFilter<"Remote"> | Date | string | null
  isFetching?: Prisma.BoolFilter<"Remote"> | boolean
  releases?: Prisma.ReleaseListRelationFilter
  latest?: Prisma.XOR<Prisma.ReleaseNullableScalarRelationFilter, Prisma.ReleaseWhereInput> | null
  usedIn?: Prisma.ServiceListRelationFilter
}

export type RemoteOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  config?: Prisma.SortOrder
  latestId?: Prisma.SortOrderInput | Prisma.SortOrder
  lastFetched?: Prisma.SortOrderInput | Prisma.SortOrder
  isFetching?: Prisma.SortOrder
  releases?: Prisma.ReleaseOrderByRelationAggregateInput
  latest?: Prisma.ReleaseOrderByWithRelationInput
  usedIn?: Prisma.ServiceOrderByRelationAggregateInput
}

export type RemoteWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  latestId?: number
  type_config?: Prisma.RemoteTypeConfigCompoundUniqueInput
  AND?: Prisma.RemoteWhereInput | Prisma.RemoteWhereInput[]
  OR?: Prisma.RemoteWhereInput[]
  NOT?: Prisma.RemoteWhereInput | Prisma.RemoteWhereInput[]
  type?: Prisma.StringFilter<"Remote"> | string
  config?: Prisma.StringFilter<"Remote"> | string
  lastFetched?: Prisma.DateTimeNullableFilter<"Remote"> | Date | string | null
  isFetching?: Prisma.BoolFilter<"Remote"> | boolean
  releases?: Prisma.ReleaseListRelationFilter
  latest?: Prisma.XOR<Prisma.ReleaseNullableScalarRelationFilter, Prisma.ReleaseWhereInput> | null
  usedIn?: Prisma.ServiceListRelationFilter
}, "id" | "latestId" | "type_config">

export type RemoteOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  config?: Prisma.SortOrder
  latestId?: Prisma.SortOrderInput | Prisma.SortOrder
  lastFetched?: Prisma.SortOrderInput | Prisma.SortOrder
  isFetching?: Prisma.SortOrder
  _count?: Prisma.RemoteCountOrderByAggregateInput
  _avg?: Prisma.RemoteAvgOrderByAggregateInput
  _max?: Prisma.RemoteMaxOrderByAggregateInput
  _min?: Prisma.RemoteMinOrderByAggregateInput
  _sum?: Prisma.RemoteSumOrderByAggregateInput
}

export type RemoteScalarWhereWithAggregatesInput = {
  AND?: Prisma.RemoteScalarWhereWithAggregatesInput | Prisma.RemoteScalarWhereWithAggregatesInput[]
  OR?: Prisma.RemoteScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RemoteScalarWhereWithAggregatesInput | Prisma.RemoteScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Remote"> | number
  type?: Prisma.StringWithAggregatesFilter<"Remote"> | string
  config?: Prisma.StringWithAggregatesFilter<"Remote"> | string
  latestId?: Prisma.IntNullableWithAggregatesFilter<"Remote"> | number | null
  lastFetched?: Prisma.DateTimeNullableWithAggregatesFilter<"Remote"> | Date | string | null
  isFetching?: Prisma.BoolWithAggregatesFilter<"Remote"> | boolean
}

export type RemoteCreateInput = {
  type: string
  config: string
  lastFetched?: Date | string | null
  isFetching?: boolean
  releases?: Prisma.ReleaseCreateNestedManyWithoutRemoteInput
  latest?: Prisma.ReleaseCreateNestedOneWithoutLatestInInput
  usedIn?: Prisma.ServiceCreateNestedManyWithoutRemoteInput
}

export type RemoteUncheckedCreateInput = {
  id?: number
  type: string
  config: string
  latestId?: number | null
  lastFetched?: Date | string | null
  isFetching?: boolean
  releases?: Prisma.ReleaseUncheckedCreateNestedManyWithoutRemoteInput
  usedIn?: Prisma.ServiceUncheckedCreateNestedManyWithoutRemoteInput
}

export type RemoteUpdateInput = {
  type?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.StringFieldUpdateOperationsInput | string
  lastFetched?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isFetching?: Prisma.BoolFieldUpdateOperationsInput | boolean
  releases?: Prisma.ReleaseUpdateManyWithoutRemoteNestedInput
  latest?: Prisma.ReleaseUpdateOneWithoutLatestInNestedInput
  usedIn?: Prisma.ServiceUpdateManyWithoutRemoteNestedInput
}

export type RemoteUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.StringFieldUpdateOperationsInput | string
  latestId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lastFetched?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isFetching?: Prisma.BoolFieldUpdateOperationsInput | boolean
  releases?: Prisma.ReleaseUncheckedUpdateManyWithoutRemoteNestedInput
  usedIn?: Prisma.ServiceUncheckedUpdateManyWithoutRemoteNestedInput
}

export type RemoteCreateManyInput = {
  id?: number
  type: string
  config: string
  latestId?: number | null
  lastFetched?: Date | string | null
  isFetching?: boolean
}

export type RemoteUpdateManyMutationInput = {
  type?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.StringFieldUpdateOperationsInput | string
  lastFetched?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isFetching?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type RemoteUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.StringFieldUpdateOperationsInput | string
  latestId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lastFetched?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isFetching?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type RemoteTypeConfigCompoundUniqueInput = {
  type: string
  config: string
}

export type RemoteCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  config?: Prisma.SortOrder
  latestId?: Prisma.SortOrder
  lastFetched?: Prisma.SortOrder
  isFetching?: Prisma.SortOrder
}

export type RemoteAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  latestId?: Prisma.SortOrder
}

export type RemoteMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  config?: Prisma.SortOrder
  latestId?: Prisma.SortOrder
  lastFetched?: Prisma.SortOrder
  isFetching?: Prisma.SortOrder
}

export type RemoteMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  config?: Prisma.SortOrder
  latestId?: Prisma.SortOrder
  lastFetched?: Prisma.SortOrder
  isFetching?: Prisma.SortOrder
}

export type RemoteSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  latestId?: Prisma.SortOrder
}

export type RemoteScalarRelationFilter = {
  is?: Prisma.RemoteWhereInput
  isNot?: Prisma.RemoteWhereInput
}

export type RemoteListRelationFilter = {
  every?: Prisma.RemoteWhereInput
  some?: Prisma.RemoteWhereInput
  none?: Prisma.RemoteWhereInput
}

export type RemoteOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RemoteNullableScalarRelationFilter = {
  is?: Prisma.RemoteWhereInput | null
  isNot?: Prisma.RemoteWhereInput | null
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type RemoteCreateNestedOneWithoutReleasesInput = {
  create?: Prisma.XOR<Prisma.RemoteCreateWithoutReleasesInput, Prisma.RemoteUncheckedCreateWithoutReleasesInput>
  connectOrCreate?: Prisma.RemoteCreateOrConnectWithoutReleasesInput
  connect?: Prisma.RemoteWhereUniqueInput
}

export type RemoteCreateNestedManyWithoutLatestInput = {
  create?: Prisma.XOR<Prisma.RemoteCreateWithoutLatestInput, Prisma.RemoteUncheckedCreateWithoutLatestInput> | Prisma.RemoteCreateWithoutLatestInput[] | Prisma.RemoteUncheckedCreateWithoutLatestInput[]
  connectOrCreate?: Prisma.RemoteCreateOrConnectWithoutLatestInput | Prisma.RemoteCreateOrConnectWithoutLatestInput[]
  createMany?: Prisma.RemoteCreateManyLatestInputEnvelope
  connect?: Prisma.RemoteWhereUniqueInput | Prisma.RemoteWhereUniqueInput[]
}

export type RemoteUncheckedCreateNestedManyWithoutLatestInput = {
  create?: Prisma.XOR<Prisma.RemoteCreateWithoutLatestInput, Prisma.RemoteUncheckedCreateWithoutLatestInput> | Prisma.RemoteCreateWithoutLatestInput[] | Prisma.RemoteUncheckedCreateWithoutLatestInput[]
  connectOrCreate?: Prisma.RemoteCreateOrConnectWithoutLatestInput | Prisma.RemoteCreateOrConnectWithoutLatestInput[]
  createMany?: Prisma.RemoteCreateManyLatestInputEnvelope
  connect?: Prisma.RemoteWhereUniqueInput | Prisma.RemoteWhereUniqueInput[]
}

export type RemoteUpdateOneRequiredWithoutReleasesNestedInput = {
  create?: Prisma.XOR<Prisma.RemoteCreateWithoutReleasesInput, Prisma.RemoteUncheckedCreateWithoutReleasesInput>
  connectOrCreate?: Prisma.RemoteCreateOrConnectWithoutReleasesInput
  upsert?: Prisma.RemoteUpsertWithoutReleasesInput
  connect?: Prisma.RemoteWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.RemoteUpdateToOneWithWhereWithoutReleasesInput, Prisma.RemoteUpdateWithoutReleasesInput>, Prisma.RemoteUncheckedUpdateWithoutReleasesInput>
}

export type RemoteUpdateManyWithoutLatestNestedInput = {
  create?: Prisma.XOR<Prisma.RemoteCreateWithoutLatestInput, Prisma.RemoteUncheckedCreateWithoutLatestInput> | Prisma.RemoteCreateWithoutLatestInput[] | Prisma.RemoteUncheckedCreateWithoutLatestInput[]
  connectOrCreate?: Prisma.RemoteCreateOrConnectWithoutLatestInput | Prisma.RemoteCreateOrConnectWithoutLatestInput[]
  upsert?: Prisma.RemoteUpsertWithWhereUniqueWithoutLatestInput | Prisma.RemoteUpsertWithWhereUniqueWithoutLatestInput[]
  createMany?: Prisma.RemoteCreateManyLatestInputEnvelope
  set?: Prisma.RemoteWhereUniqueInput | Prisma.RemoteWhereUniqueInput[]
  disconnect?: Prisma.RemoteWhereUniqueInput | Prisma.RemoteWhereUniqueInput[]
  delete?: Prisma.RemoteWhereUniqueInput | Prisma.RemoteWhereUniqueInput[]
  connect?: Prisma.RemoteWhereUniqueInput | Prisma.RemoteWhereUniqueInput[]
  update?: Prisma.RemoteUpdateWithWhereUniqueWithoutLatestInput | Prisma.RemoteUpdateWithWhereUniqueWithoutLatestInput[]
  updateMany?: Prisma.RemoteUpdateManyWithWhereWithoutLatestInput | Prisma.RemoteUpdateManyWithWhereWithoutLatestInput[]
  deleteMany?: Prisma.RemoteScalarWhereInput | Prisma.RemoteScalarWhereInput[]
}

export type RemoteUncheckedUpdateManyWithoutLatestNestedInput = {
  create?: Prisma.XOR<Prisma.RemoteCreateWithoutLatestInput, Prisma.RemoteUncheckedCreateWithoutLatestInput> | Prisma.RemoteCreateWithoutLatestInput[] | Prisma.RemoteUncheckedCreateWithoutLatestInput[]
  connectOrCreate?: Prisma.RemoteCreateOrConnectWithoutLatestInput | Prisma.RemoteCreateOrConnectWithoutLatestInput[]
  upsert?: Prisma.RemoteUpsertWithWhereUniqueWithoutLatestInput | Prisma.RemoteUpsertWithWhereUniqueWithoutLatestInput[]
  createMany?: Prisma.RemoteCreateManyLatestInputEnvelope
  set?: Prisma.RemoteWhereUniqueInput | Prisma.RemoteWhereUniqueInput[]
  disconnect?: Prisma.RemoteWhereUniqueInput | Prisma.RemoteWhereUniqueInput[]
  delete?: Prisma.RemoteWhereUniqueInput | Prisma.RemoteWhereUniqueInput[]
  connect?: Prisma.RemoteWhereUniqueInput | Prisma.RemoteWhereUniqueInput[]
  update?: Prisma.RemoteUpdateWithWhereUniqueWithoutLatestInput | Prisma.RemoteUpdateWithWhereUniqueWithoutLatestInput[]
  updateMany?: Prisma.RemoteUpdateManyWithWhereWithoutLatestInput | Prisma.RemoteUpdateManyWithWhereWithoutLatestInput[]
  deleteMany?: Prisma.RemoteScalarWhereInput | Prisma.RemoteScalarWhereInput[]
}

export type RemoteCreateNestedOneWithoutUsedInInput = {
  create?: Prisma.XOR<Prisma.RemoteCreateWithoutUsedInInput, Prisma.RemoteUncheckedCreateWithoutUsedInInput>
  connectOrCreate?: Prisma.RemoteCreateOrConnectWithoutUsedInInput
  connect?: Prisma.RemoteWhereUniqueInput
}

export type RemoteUpdateOneWithoutUsedInNestedInput = {
  create?: Prisma.XOR<Prisma.RemoteCreateWithoutUsedInInput, Prisma.RemoteUncheckedCreateWithoutUsedInInput>
  connectOrCreate?: Prisma.RemoteCreateOrConnectWithoutUsedInInput
  upsert?: Prisma.RemoteUpsertWithoutUsedInInput
  disconnect?: Prisma.RemoteWhereInput | boolean
  delete?: Prisma.RemoteWhereInput | boolean
  connect?: Prisma.RemoteWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.RemoteUpdateToOneWithWhereWithoutUsedInInput, Prisma.RemoteUpdateWithoutUsedInInput>, Prisma.RemoteUncheckedUpdateWithoutUsedInInput>
}

export type RemoteCreateWithoutReleasesInput = {
  type: string
  config: string
  lastFetched?: Date | string | null
  isFetching?: boolean
  latest?: Prisma.ReleaseCreateNestedOneWithoutLatestInInput
  usedIn?: Prisma.ServiceCreateNestedManyWithoutRemoteInput
}

export type RemoteUncheckedCreateWithoutReleasesInput = {
  id?: number
  type: string
  config: string
  latestId?: number | null
  lastFetched?: Date | string | null
  isFetching?: boolean
  usedIn?: Prisma.ServiceUncheckedCreateNestedManyWithoutRemoteInput
}

export type RemoteCreateOrConnectWithoutReleasesInput = {
  where: Prisma.RemoteWhereUniqueInput
  create: Prisma.XOR<Prisma.RemoteCreateWithoutReleasesInput, Prisma.RemoteUncheckedCreateWithoutReleasesInput>
}

export type RemoteCreateWithoutLatestInput = {
  type: string
  config: string
  lastFetched?: Date | string | null
  isFetching?: boolean
  releases?: Prisma.ReleaseCreateNestedManyWithoutRemoteInput
  usedIn?: Prisma.ServiceCreateNestedManyWithoutRemoteInput
}

export type RemoteUncheckedCreateWithoutLatestInput = {
  id?: number
  type: string
  config: string
  lastFetched?: Date | string | null
  isFetching?: boolean
  releases?: Prisma.ReleaseUncheckedCreateNestedManyWithoutRemoteInput
  usedIn?: Prisma.ServiceUncheckedCreateNestedManyWithoutRemoteInput
}

export type RemoteCreateOrConnectWithoutLatestInput = {
  where: Prisma.RemoteWhereUniqueInput
  create: Prisma.XOR<Prisma.RemoteCreateWithoutLatestInput, Prisma.RemoteUncheckedCreateWithoutLatestInput>
}

export type RemoteCreateManyLatestInputEnvelope = {
  data: Prisma.RemoteCreateManyLatestInput | Prisma.RemoteCreateManyLatestInput[]
}

export type RemoteUpsertWithoutReleasesInput = {
  update: Prisma.XOR<Prisma.RemoteUpdateWithoutReleasesInput, Prisma.RemoteUncheckedUpdateWithoutReleasesInput>
  create: Prisma.XOR<Prisma.RemoteCreateWithoutReleasesInput, Prisma.RemoteUncheckedCreateWithoutReleasesInput>
  where?: Prisma.RemoteWhereInput
}

export type RemoteUpdateToOneWithWhereWithoutReleasesInput = {
  where?: Prisma.RemoteWhereInput
  data: Prisma.XOR<Prisma.RemoteUpdateWithoutReleasesInput, Prisma.RemoteUncheckedUpdateWithoutReleasesInput>
}

export type RemoteUpdateWithoutReleasesInput = {
  type?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.StringFieldUpdateOperationsInput | string
  lastFetched?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isFetching?: Prisma.BoolFieldUpdateOperationsInput | boolean
  latest?: Prisma.ReleaseUpdateOneWithoutLatestInNestedInput
  usedIn?: Prisma.ServiceUpdateManyWithoutRemoteNestedInput
}

export type RemoteUncheckedUpdateWithoutReleasesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.StringFieldUpdateOperationsInput | string
  latestId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lastFetched?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isFetching?: Prisma.BoolFieldUpdateOperationsInput | boolean
  usedIn?: Prisma.ServiceUncheckedUpdateManyWithoutRemoteNestedInput
}

export type RemoteUpsertWithWhereUniqueWithoutLatestInput = {
  where: Prisma.RemoteWhereUniqueInput
  update: Prisma.XOR<Prisma.RemoteUpdateWithoutLatestInput, Prisma.RemoteUncheckedUpdateWithoutLatestInput>
  create: Prisma.XOR<Prisma.RemoteCreateWithoutLatestInput, Prisma.RemoteUncheckedCreateWithoutLatestInput>
}

export type RemoteUpdateWithWhereUniqueWithoutLatestInput = {
  where: Prisma.RemoteWhereUniqueInput
  data: Prisma.XOR<Prisma.RemoteUpdateWithoutLatestInput, Prisma.RemoteUncheckedUpdateWithoutLatestInput>
}

export type RemoteUpdateManyWithWhereWithoutLatestInput = {
  where: Prisma.RemoteScalarWhereInput
  data: Prisma.XOR<Prisma.RemoteUpdateManyMutationInput, Prisma.RemoteUncheckedUpdateManyWithoutLatestInput>
}

export type RemoteScalarWhereInput = {
  AND?: Prisma.RemoteScalarWhereInput | Prisma.RemoteScalarWhereInput[]
  OR?: Prisma.RemoteScalarWhereInput[]
  NOT?: Prisma.RemoteScalarWhereInput | Prisma.RemoteScalarWhereInput[]
  id?: Prisma.IntFilter<"Remote"> | number
  type?: Prisma.StringFilter<"Remote"> | string
  config?: Prisma.StringFilter<"Remote"> | string
  latestId?: Prisma.IntNullableFilter<"Remote"> | number | null
  lastFetched?: Prisma.DateTimeNullableFilter<"Remote"> | Date | string | null
  isFetching?: Prisma.BoolFilter<"Remote"> | boolean
}

export type RemoteCreateWithoutUsedInInput = {
  type: string
  config: string
  lastFetched?: Date | string | null
  isFetching?: boolean
  releases?: Prisma.ReleaseCreateNestedManyWithoutRemoteInput
  latest?: Prisma.ReleaseCreateNestedOneWithoutLatestInInput
}

export type RemoteUncheckedCreateWithoutUsedInInput = {
  id?: number
  type: string
  config: string
  latestId?: number | null
  lastFetched?: Date | string | null
  isFetching?: boolean
  releases?: Prisma.ReleaseUncheckedCreateNestedManyWithoutRemoteInput
}

export type RemoteCreateOrConnectWithoutUsedInInput = {
  where: Prisma.RemoteWhereUniqueInput
  create: Prisma.XOR<Prisma.RemoteCreateWithoutUsedInInput, Prisma.RemoteUncheckedCreateWithoutUsedInInput>
}

export type RemoteUpsertWithoutUsedInInput = {
  update: Prisma.XOR<Prisma.RemoteUpdateWithoutUsedInInput, Prisma.RemoteUncheckedUpdateWithoutUsedInInput>
  create: Prisma.XOR<Prisma.RemoteCreateWithoutUsedInInput, Prisma.RemoteUncheckedCreateWithoutUsedInInput>
  where?: Prisma.RemoteWhereInput
}

export type RemoteUpdateToOneWithWhereWithoutUsedInInput = {
  where?: Prisma.RemoteWhereInput
  data: Prisma.XOR<Prisma.RemoteUpdateWithoutUsedInInput, Prisma.RemoteUncheckedUpdateWithoutUsedInInput>
}

export type RemoteUpdateWithoutUsedInInput = {
  type?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.StringFieldUpdateOperationsInput | string
  lastFetched?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isFetching?: Prisma.BoolFieldUpdateOperationsInput | boolean
  releases?: Prisma.ReleaseUpdateManyWithoutRemoteNestedInput
  latest?: Prisma.ReleaseUpdateOneWithoutLatestInNestedInput
}

export type RemoteUncheckedUpdateWithoutUsedInInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.StringFieldUpdateOperationsInput | string
  latestId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lastFetched?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isFetching?: Prisma.BoolFieldUpdateOperationsInput | boolean
  releases?: Prisma.ReleaseUncheckedUpdateManyWithoutRemoteNestedInput
}

export type RemoteCreateManyLatestInput = {
  id?: number
  type: string
  config: string
  lastFetched?: Date | string | null
  isFetching?: boolean
}

export type RemoteUpdateWithoutLatestInput = {
  type?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.StringFieldUpdateOperationsInput | string
  lastFetched?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isFetching?: Prisma.BoolFieldUpdateOperationsInput | boolean
  releases?: Prisma.ReleaseUpdateManyWithoutRemoteNestedInput
  usedIn?: Prisma.ServiceUpdateManyWithoutRemoteNestedInput
}

export type RemoteUncheckedUpdateWithoutLatestInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.StringFieldUpdateOperationsInput | string
  lastFetched?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isFetching?: Prisma.BoolFieldUpdateOperationsInput | boolean
  releases?: Prisma.ReleaseUncheckedUpdateManyWithoutRemoteNestedInput
  usedIn?: Prisma.ServiceUncheckedUpdateManyWithoutRemoteNestedInput
}

export type RemoteUncheckedUpdateManyWithoutLatestInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.StringFieldUpdateOperationsInput | string
  lastFetched?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isFetching?: Prisma.BoolFieldUpdateOperationsInput | boolean
}


/**
 * Count Type RemoteCountOutputType
 */

export type RemoteCountOutputType = {
  releases: number
  usedIn: number
}

export type RemoteCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  releases?: boolean | RemoteCountOutputTypeCountReleasesArgs
  usedIn?: boolean | RemoteCountOutputTypeCountUsedInArgs
}

/**
 * RemoteCountOutputType without action
 */
export type RemoteCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RemoteCountOutputType
   */
  select?: Prisma.RemoteCountOutputTypeSelect<ExtArgs> | null
}

/**
 * RemoteCountOutputType without action
 */
export type RemoteCountOutputTypeCountReleasesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReleaseWhereInput
}

/**
 * RemoteCountOutputType without action
 */
export type RemoteCountOutputTypeCountUsedInArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ServiceWhereInput
}


export type RemoteSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  config?: boolean
  latestId?: boolean
  lastFetched?: boolean
  isFetching?: boolean
  releases?: boolean | Prisma.Remote$releasesArgs<ExtArgs>
  latest?: boolean | Prisma.Remote$latestArgs<ExtArgs>
  usedIn?: boolean | Prisma.Remote$usedInArgs<ExtArgs>
  _count?: boolean | Prisma.RemoteCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["remote"]>

export type RemoteSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  config?: boolean
  latestId?: boolean
  lastFetched?: boolean
  isFetching?: boolean
  latest?: boolean | Prisma.Remote$latestArgs<ExtArgs>
}, ExtArgs["result"]["remote"]>

export type RemoteSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  config?: boolean
  latestId?: boolean
  lastFetched?: boolean
  isFetching?: boolean
  latest?: boolean | Prisma.Remote$latestArgs<ExtArgs>
}, ExtArgs["result"]["remote"]>

export type RemoteSelectScalar = {
  id?: boolean
  type?: boolean
  config?: boolean
  latestId?: boolean
  lastFetched?: boolean
  isFetching?: boolean
}

export type RemoteOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "type" | "config" | "latestId" | "lastFetched" | "isFetching", ExtArgs["result"]["remote"]>
export type RemoteInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  releases?: boolean | Prisma.Remote$releasesArgs<ExtArgs>
  latest?: boolean | Prisma.Remote$latestArgs<ExtArgs>
  usedIn?: boolean | Prisma.Remote$usedInArgs<ExtArgs>
  _count?: boolean | Prisma.RemoteCountOutputTypeDefaultArgs<ExtArgs>
}
export type RemoteIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  latest?: boolean | Prisma.Remote$latestArgs<ExtArgs>
}
export type RemoteIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  latest?: boolean | Prisma.Remote$latestArgs<ExtArgs>
}

export type $RemotePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Remote"
  objects: {
    releases: Prisma.$ReleasePayload<ExtArgs>[]
    latest: Prisma.$ReleasePayload<ExtArgs> | null
    usedIn: Prisma.$ServicePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    type: string
    config: string
    latestId: number | null
    lastFetched: Date | null
    isFetching: boolean
  }, ExtArgs["result"]["remote"]>
  composites: {}
}

export type RemoteGetPayload<S extends boolean | null | undefined | RemoteDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RemotePayload, S>

export type RemoteCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RemoteFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RemoteCountAggregateInputType | true
  }

export interface RemoteDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Remote'], meta: { name: 'Remote' } }
  /**
   * Find zero or one Remote that matches the filter.
   * @param {RemoteFindUniqueArgs} args - Arguments to find a Remote
   * @example
   * // Get one Remote
   * const remote = await prisma.remote.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RemoteFindUniqueArgs>(args: Prisma.SelectSubset<T, RemoteFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RemoteClient<runtime.Types.Result.GetResult<Prisma.$RemotePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Remote that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RemoteFindUniqueOrThrowArgs} args - Arguments to find a Remote
   * @example
   * // Get one Remote
   * const remote = await prisma.remote.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RemoteFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RemoteFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RemoteClient<runtime.Types.Result.GetResult<Prisma.$RemotePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Remote that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RemoteFindFirstArgs} args - Arguments to find a Remote
   * @example
   * // Get one Remote
   * const remote = await prisma.remote.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RemoteFindFirstArgs>(args?: Prisma.SelectSubset<T, RemoteFindFirstArgs<ExtArgs>>): Prisma.Prisma__RemoteClient<runtime.Types.Result.GetResult<Prisma.$RemotePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Remote that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RemoteFindFirstOrThrowArgs} args - Arguments to find a Remote
   * @example
   * // Get one Remote
   * const remote = await prisma.remote.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RemoteFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RemoteFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RemoteClient<runtime.Types.Result.GetResult<Prisma.$RemotePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Remotes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RemoteFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Remotes
   * const remotes = await prisma.remote.findMany()
   * 
   * // Get first 10 Remotes
   * const remotes = await prisma.remote.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const remoteWithIdOnly = await prisma.remote.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RemoteFindManyArgs>(args?: Prisma.SelectSubset<T, RemoteFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RemotePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Remote.
   * @param {RemoteCreateArgs} args - Arguments to create a Remote.
   * @example
   * // Create one Remote
   * const Remote = await prisma.remote.create({
   *   data: {
   *     // ... data to create a Remote
   *   }
   * })
   * 
   */
  create<T extends RemoteCreateArgs>(args: Prisma.SelectSubset<T, RemoteCreateArgs<ExtArgs>>): Prisma.Prisma__RemoteClient<runtime.Types.Result.GetResult<Prisma.$RemotePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Remotes.
   * @param {RemoteCreateManyArgs} args - Arguments to create many Remotes.
   * @example
   * // Create many Remotes
   * const remote = await prisma.remote.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RemoteCreateManyArgs>(args?: Prisma.SelectSubset<T, RemoteCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Remotes and returns the data saved in the database.
   * @param {RemoteCreateManyAndReturnArgs} args - Arguments to create many Remotes.
   * @example
   * // Create many Remotes
   * const remote = await prisma.remote.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Remotes and only return the `id`
   * const remoteWithIdOnly = await prisma.remote.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RemoteCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RemoteCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RemotePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Remote.
   * @param {RemoteDeleteArgs} args - Arguments to delete one Remote.
   * @example
   * // Delete one Remote
   * const Remote = await prisma.remote.delete({
   *   where: {
   *     // ... filter to delete one Remote
   *   }
   * })
   * 
   */
  delete<T extends RemoteDeleteArgs>(args: Prisma.SelectSubset<T, RemoteDeleteArgs<ExtArgs>>): Prisma.Prisma__RemoteClient<runtime.Types.Result.GetResult<Prisma.$RemotePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Remote.
   * @param {RemoteUpdateArgs} args - Arguments to update one Remote.
   * @example
   * // Update one Remote
   * const remote = await prisma.remote.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RemoteUpdateArgs>(args: Prisma.SelectSubset<T, RemoteUpdateArgs<ExtArgs>>): Prisma.Prisma__RemoteClient<runtime.Types.Result.GetResult<Prisma.$RemotePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Remotes.
   * @param {RemoteDeleteManyArgs} args - Arguments to filter Remotes to delete.
   * @example
   * // Delete a few Remotes
   * const { count } = await prisma.remote.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RemoteDeleteManyArgs>(args?: Prisma.SelectSubset<T, RemoteDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Remotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RemoteUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Remotes
   * const remote = await prisma.remote.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RemoteUpdateManyArgs>(args: Prisma.SelectSubset<T, RemoteUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Remotes and returns the data updated in the database.
   * @param {RemoteUpdateManyAndReturnArgs} args - Arguments to update many Remotes.
   * @example
   * // Update many Remotes
   * const remote = await prisma.remote.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Remotes and only return the `id`
   * const remoteWithIdOnly = await prisma.remote.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RemoteUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RemoteUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RemotePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Remote.
   * @param {RemoteUpsertArgs} args - Arguments to update or create a Remote.
   * @example
   * // Update or create a Remote
   * const remote = await prisma.remote.upsert({
   *   create: {
   *     // ... data to create a Remote
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Remote we want to update
   *   }
   * })
   */
  upsert<T extends RemoteUpsertArgs>(args: Prisma.SelectSubset<T, RemoteUpsertArgs<ExtArgs>>): Prisma.Prisma__RemoteClient<runtime.Types.Result.GetResult<Prisma.$RemotePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Remotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RemoteCountArgs} args - Arguments to filter Remotes to count.
   * @example
   * // Count the number of Remotes
   * const count = await prisma.remote.count({
   *   where: {
   *     // ... the filter for the Remotes we want to count
   *   }
   * })
  **/
  count<T extends RemoteCountArgs>(
    args?: Prisma.Subset<T, RemoteCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RemoteCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Remote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RemoteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RemoteAggregateArgs>(args: Prisma.Subset<T, RemoteAggregateArgs>): Prisma.PrismaPromise<GetRemoteAggregateType<T>>

  /**
   * Group by Remote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RemoteGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RemoteGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RemoteGroupByArgs['orderBy'] }
      : { orderBy?: RemoteGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RemoteGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRemoteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Remote model
 */
readonly fields: RemoteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Remote.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RemoteClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  releases<T extends Prisma.Remote$releasesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Remote$releasesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReleasePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  latest<T extends Prisma.Remote$latestArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Remote$latestArgs<ExtArgs>>): Prisma.Prisma__ReleaseClient<runtime.Types.Result.GetResult<Prisma.$ReleasePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  usedIn<T extends Prisma.Remote$usedInArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Remote$usedInArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServicePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Remote model
 */
export interface RemoteFieldRefs {
  readonly id: Prisma.FieldRef<"Remote", 'Int'>
  readonly type: Prisma.FieldRef<"Remote", 'String'>
  readonly config: Prisma.FieldRef<"Remote", 'String'>
  readonly latestId: Prisma.FieldRef<"Remote", 'Int'>
  readonly lastFetched: Prisma.FieldRef<"Remote", 'DateTime'>
  readonly isFetching: Prisma.FieldRef<"Remote", 'Boolean'>
}
    

// Custom InputTypes
/**
 * Remote findUnique
 */
export type RemoteFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Remote
   */
  select?: Prisma.RemoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Remote
   */
  omit?: Prisma.RemoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemoteInclude<ExtArgs> | null
  /**
   * Filter, which Remote to fetch.
   */
  where: Prisma.RemoteWhereUniqueInput
}

/**
 * Remote findUniqueOrThrow
 */
export type RemoteFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Remote
   */
  select?: Prisma.RemoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Remote
   */
  omit?: Prisma.RemoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemoteInclude<ExtArgs> | null
  /**
   * Filter, which Remote to fetch.
   */
  where: Prisma.RemoteWhereUniqueInput
}

/**
 * Remote findFirst
 */
export type RemoteFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Remote
   */
  select?: Prisma.RemoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Remote
   */
  omit?: Prisma.RemoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemoteInclude<ExtArgs> | null
  /**
   * Filter, which Remote to fetch.
   */
  where?: Prisma.RemoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Remotes to fetch.
   */
  orderBy?: Prisma.RemoteOrderByWithRelationInput | Prisma.RemoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Remotes.
   */
  cursor?: Prisma.RemoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Remotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Remotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Remotes.
   */
  distinct?: Prisma.RemoteScalarFieldEnum | Prisma.RemoteScalarFieldEnum[]
}

/**
 * Remote findFirstOrThrow
 */
export type RemoteFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Remote
   */
  select?: Prisma.RemoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Remote
   */
  omit?: Prisma.RemoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemoteInclude<ExtArgs> | null
  /**
   * Filter, which Remote to fetch.
   */
  where?: Prisma.RemoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Remotes to fetch.
   */
  orderBy?: Prisma.RemoteOrderByWithRelationInput | Prisma.RemoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Remotes.
   */
  cursor?: Prisma.RemoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Remotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Remotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Remotes.
   */
  distinct?: Prisma.RemoteScalarFieldEnum | Prisma.RemoteScalarFieldEnum[]
}

/**
 * Remote findMany
 */
export type RemoteFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Remote
   */
  select?: Prisma.RemoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Remote
   */
  omit?: Prisma.RemoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemoteInclude<ExtArgs> | null
  /**
   * Filter, which Remotes to fetch.
   */
  where?: Prisma.RemoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Remotes to fetch.
   */
  orderBy?: Prisma.RemoteOrderByWithRelationInput | Prisma.RemoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Remotes.
   */
  cursor?: Prisma.RemoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Remotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Remotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Remotes.
   */
  distinct?: Prisma.RemoteScalarFieldEnum | Prisma.RemoteScalarFieldEnum[]
}

/**
 * Remote create
 */
export type RemoteCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Remote
   */
  select?: Prisma.RemoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Remote
   */
  omit?: Prisma.RemoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemoteInclude<ExtArgs> | null
  /**
   * The data needed to create a Remote.
   */
  data: Prisma.XOR<Prisma.RemoteCreateInput, Prisma.RemoteUncheckedCreateInput>
}

/**
 * Remote createMany
 */
export type RemoteCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Remotes.
   */
  data: Prisma.RemoteCreateManyInput | Prisma.RemoteCreateManyInput[]
}

/**
 * Remote createManyAndReturn
 */
export type RemoteCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Remote
   */
  select?: Prisma.RemoteSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Remote
   */
  omit?: Prisma.RemoteOmit<ExtArgs> | null
  /**
   * The data used to create many Remotes.
   */
  data: Prisma.RemoteCreateManyInput | Prisma.RemoteCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemoteIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Remote update
 */
export type RemoteUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Remote
   */
  select?: Prisma.RemoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Remote
   */
  omit?: Prisma.RemoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemoteInclude<ExtArgs> | null
  /**
   * The data needed to update a Remote.
   */
  data: Prisma.XOR<Prisma.RemoteUpdateInput, Prisma.RemoteUncheckedUpdateInput>
  /**
   * Choose, which Remote to update.
   */
  where: Prisma.RemoteWhereUniqueInput
}

/**
 * Remote updateMany
 */
export type RemoteUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Remotes.
   */
  data: Prisma.XOR<Prisma.RemoteUpdateManyMutationInput, Prisma.RemoteUncheckedUpdateManyInput>
  /**
   * Filter which Remotes to update
   */
  where?: Prisma.RemoteWhereInput
  /**
   * Limit how many Remotes to update.
   */
  limit?: number
}

/**
 * Remote updateManyAndReturn
 */
export type RemoteUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Remote
   */
  select?: Prisma.RemoteSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Remote
   */
  omit?: Prisma.RemoteOmit<ExtArgs> | null
  /**
   * The data used to update Remotes.
   */
  data: Prisma.XOR<Prisma.RemoteUpdateManyMutationInput, Prisma.RemoteUncheckedUpdateManyInput>
  /**
   * Filter which Remotes to update
   */
  where?: Prisma.RemoteWhereInput
  /**
   * Limit how many Remotes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemoteIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Remote upsert
 */
export type RemoteUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Remote
   */
  select?: Prisma.RemoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Remote
   */
  omit?: Prisma.RemoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemoteInclude<ExtArgs> | null
  /**
   * The filter to search for the Remote to update in case it exists.
   */
  where: Prisma.RemoteWhereUniqueInput
  /**
   * In case the Remote found by the `where` argument doesn't exist, create a new Remote with this data.
   */
  create: Prisma.XOR<Prisma.RemoteCreateInput, Prisma.RemoteUncheckedCreateInput>
  /**
   * In case the Remote was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RemoteUpdateInput, Prisma.RemoteUncheckedUpdateInput>
}

/**
 * Remote delete
 */
export type RemoteDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Remote
   */
  select?: Prisma.RemoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Remote
   */
  omit?: Prisma.RemoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemoteInclude<ExtArgs> | null
  /**
   * Filter which Remote to delete.
   */
  where: Prisma.RemoteWhereUniqueInput
}

/**
 * Remote deleteMany
 */
export type RemoteDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Remotes to delete
   */
  where?: Prisma.RemoteWhereInput
  /**
   * Limit how many Remotes to delete.
   */
  limit?: number
}

/**
 * Remote.releases
 */
export type Remote$releasesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Release
   */
  select?: Prisma.ReleaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Release
   */
  omit?: Prisma.ReleaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReleaseInclude<ExtArgs> | null
  where?: Prisma.ReleaseWhereInput
  orderBy?: Prisma.ReleaseOrderByWithRelationInput | Prisma.ReleaseOrderByWithRelationInput[]
  cursor?: Prisma.ReleaseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ReleaseScalarFieldEnum | Prisma.ReleaseScalarFieldEnum[]
}

/**
 * Remote.latest
 */
export type Remote$latestArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Release
   */
  select?: Prisma.ReleaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Release
   */
  omit?: Prisma.ReleaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReleaseInclude<ExtArgs> | null
  where?: Prisma.ReleaseWhereInput
}

/**
 * Remote.usedIn
 */
export type Remote$usedInArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Service
   */
  select?: Prisma.ServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Service
   */
  omit?: Prisma.ServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceInclude<ExtArgs> | null
  where?: Prisma.ServiceWhereInput
  orderBy?: Prisma.ServiceOrderByWithRelationInput | Prisma.ServiceOrderByWithRelationInput[]
  cursor?: Prisma.ServiceWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ServiceScalarFieldEnum | Prisma.ServiceScalarFieldEnum[]
}

/**
 * Remote without action
 */
export type RemoteDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Remote
   */
  select?: Prisma.RemoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Remote
   */
  omit?: Prisma.RemoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RemoteInclude<ExtArgs> | null
}
